title: Auto-Trading Bot
description: Multi-strategy cryptocurrency trading bot using FreqTrade with Docker
url: "https://peteretelej.github.io"
baseurl: "/auto-trading"

# Build settings
markdown: kramdown
highlighter: rouge
remote_theme: pages-themes/leap-day@v0.2.0

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme

# Theme specific settings
show_downloads: false

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  # Main pages
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  # Getting started and concept guides
  - scope:
      path: "docs/getting-started.md"
    values:
      layout: "default"
      nav_order: 1
  - scope:
      path: "docs/concepts.md"
    values:
      layout: "default"
      nav_order: 2
  # Setup guides
  - scope:
      path: "docs/setup"
    values:
      layout: "default"
      nav_order: 3
      parent: "Setup Guides"
  # Usage guides  
  - scope:
      path: "docs/usage"
    values:
      layout: "default"
      nav_order: 4
      parent: "Usage Guides"
  # Reference documentation
  - scope:
      path: "docs/reference"
    values:
      layout: "default"
      nav_order: 5
      parent: "Reference"
  # Collections
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "default"

# Exclude files
exclude:
  - .env.sample
  - .gitignore
  - Dockerfile
  - docker-launch.sh
  - scripts/
  - config/
  - user_data/
  - ta-lib/
  - ta-lib-0.4.0-src.tar.gz
  - requirements.txt
  - debug.log
  - debug2.log
  - docs/legacy/